# Generated by Django 4.0.2 on 2022-02-26 11:34

import django.core.validators
from django.db import migrations, models
import expense_tracker.main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('expense_image', models.ImageField(upload_to='')),
                ('description', models.URLField(blank=True, null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), expense_tracker.main.validators.only_letter_validator])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator, expense_tracker.main.validators.only_letter_validator])),
                ('budget', models.FloatField(default=0, validators=[expense_tracker.main.validators.positive_num_validator])),
                ('profile_image', models.ImageField(blank=True, default='images/user.png', null=True, upload_to='', validators=[expense_tracker.main.validators.MaxFileSizeInMbValidator])),
            ],
        ),
    ]
