# Generated by Django 4.0.2 on 2022-02-26 21:25

import django.core.validators
from django.db import migrations, models
import expense_tracker.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_expense_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.FloatField(validators=[expense_tracker.main.validators.positive_num_validator, django.core.validators.MinValueValidator(0)]),
        ),
    ]
